mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8888
bbq:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
spring:
  profiles:
    active: pro
  resources:
    static-locations:

# Change the directory of this section when deploying
upload:
  path: /usr/bbq/upload/