spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbq?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: ff123456
shiro-redis:
  enabled: true
  redis-manager:
    host: 192.168.11.128:6379
    password: 123321
