version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
  redis:
    image: redis:latest
  bbq:
    image: bbq:latest
    build: .
    ports:
    - 8888:8888
    depends_on:
      - mysql
      - redis
